import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/alf.png'
import AnimatedText from '@/components/AnimatedText'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import Rotate from '@/components/Rotate'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
         <Layout className='pt-0'>
          <div  className='flex flex-col md:flex-row items-center justify-between w-full'>
            <div className='md:w-2/5 w-full flex justify-center md:justify-end'>
              <Image 
                src={profilePic} 
                alt='CodeBucks' 
                width={360}   
                height={360} 
                className='rounded-full'  
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Hello, It's Me Raheethus Alfer" className='!text-6xl !text-left' />
              <p className='my-4 text-base font-medium'>
                I am a full-stack developer proficient in creating web applications with modern technologies such as React, Node.js, React Native, Spring Boot, MySQL, and MongoDB. 
                My passion lies in developing software that enriches user experiences. I am always eager to embrace new challenges and opportunities to enhance my skills and advance my career as a developer.
              </p>
              <div className='flex items-center self-start mt-2'>
                <a href='/dummy.pdf' target={'_blank'}
                  className='flex items-center bg-dark text-light p-2.5 px-6
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border border-solid border-transparent hover:border-dark

                  dark:bg-light dark:text-dark hover:dark hover:dark:text-light
                  hover:dark:border-light
                  '
                  download={true}>
                  Resume <LinkArrow className={'w-6 ml-1'} />
                </a>
                <a href='mailto:ammralfer@gmail.com' target={'_blank'}
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'>
                  Contact
                </a>
              </div>
            </div>
            
          </div>
          
          
         </Layout>
         <HireMe/>
      </main>
    </>
  )
}
